
== TECHNOLOGY TRANSFER
The Parties affirm the importance of ensuring that the transfer of technology occurs on voluntary, market-based terms and recognize that forced technology transfer is a significant concern. The Parties further recognize the importance of undertaking steps to address these issues, in light of the profound impact of technology and technological change on the world economy.

To enhance mutual trust and cooperation between the Parties with respect to technology issues, protect intellectual property, promote trade and investment, and establish a foundation for addressing long-standing structural concerns, the Parties have agreed as follows:


=== Article 2.1: General Obligations
1. Natural or legal persons ("`persons`") of a Party shall have effective access to and be able to operate openly and freely in the jurisdiction of the other Party without any force or pressure from the other Party to transfer their technology to persons of the other Party.

2. Any transfer or licensing of technology between persons of a Party and those of the other Party must be based on market terms that are voluntary and reflect mutual agreement.

3. A Party shall not support or direct the outbound foreign direct investment activities of its persons aimed at acquiring foreign technology with respect to sectors and industries targeted by its industrial plans that create distortion.


=== Article 2.2: Market Access
Neither Party shall require or pressure persons of the other Party to transfer technology to its persons in relation to acquisitions, joint ventures, or other investment transactions.

=== Article 2.3: Administrative and Licensing Requirements and Processes
1. Neither Party shall adopt or maintain administrative and licensing requirements and processes that require or pressure technology transfer from persons of the other Party to its persons.

2. Neither Party shall require or pressure, formally or informally, persons of the other Party to transfer technology to its persons as a condition for, inter alia:

. approving any administrative or licensing requirements;
. operating in the jurisdiction of the Party or otherwise having access to the Party's market; or
. receiving or continuing to receive any advantages conferred by the Party.

3. Neither Party shall require or pressure, formally or informally, persons of the other Party to use or favor technology that is owned by or licensed to its persons as a condition for, inter alia:

. approving any administrative or licensing requirements;
. operating in the jurisdiction of the Party, or otherwise having access to the Party's market; or
. receiving or continuing to receive any advantages conferred by the Party.

4. The Parties shall make their administrative and licensing requirements and processes transparent.

5. The Parties shall not require or pressure foreign persons to disclose sensitive technical information not necessary to show conformity with the relevant administrative or regulatory
requirements.

6. The Parties shall protect the confidentiality of any sensitive technical information disclosed by foreign persons during any administrative, regulatory, or other review processes.


=== Article 2.4: Due Process and Transparency
1. The Parties shall ensure that any enforcement of laws and regulations with respect to persons of the other Party is impartial, fair, transparent, and non-discriminatory.

2. The Parties shall ensure that rules of procedure for administrative proceedings related to the subject matter of this Agreement are published and provide meaningful notice regarding, at a minimum, the subject matter of the proceeding, applicable laws and regulations, rules of evidence, and relevant remedies and sanctions.

3. The Parties shall provide that persons of the other Party have the right to:

. review evidence and have a meaningful opportunity to respond in any administrative proceedings against them; and
. be represented by legal counsel in administrative proceedings.

=== Article 2.5: Scientific and Technological Cooperation
The Parties agree to carry out scientific and technological cooperation where appropriate.