
== TRADE IN FOOD AND AGRICULTURAL PRODUCTS
footnote:[Article 8.5 (Final Provisions) shall not apply with respect to any proposed or final measure, including an amendment to an existing measure, intended to implement this Chapter, including its Annexes and Appendices.]


=== Article 3.1: General
1. To enhance mutual trust and friendly cooperation between China and the United States on issues affecting agricultural trade, to establish a foundation for addressing long-standing concerns, and to make agriculture a strong pillar of the bilateral relationship, the Parties:

. recognizing the importance of their agriculture sectors, of ensuring safe and reliable supplies of food and agricultural products, and of helping to meet the demand of the two countries' peoples for food and agricultural products, intend to intensify cooperation in agriculture, to expand each Party's market for food and agricultural products, and to promote the growth of trade in food and agricultural products between the Parties;
. considering that science- and risk-based sanitary and phytosanitary (SPS) measures play a crucial role in the protection of human, animal, and plant life and health, while the use of SPS measures for purposes of protectionism negatively impacts the welfare of consumers and producers, and recognizing the importance of ensuring that SPS measures are science-based, non-discriminatory, and account for regional differences in sanitary and phytosanitary characteristics, agree that neither Party shall apply sanitary or phytosanitary measures in a manner which would constitute a disguised restriction on international trade;
. considering that the benefits of an agricultural trading system are reduced when importers and exporters are unfairly impeded from taking full advantage of agricultural market access opportunities, recognize that tariff-rate quota (TRQ)
administration should not be employed as a means of preventing the full utilization of agricultural TRQs;
. noting the ability of agricultural biotechnology to improve lives by helping to feed growing populations, by reducing the environmental impact of agriculture, and by promoting more sustainable production, intend to maintain, for products of
agricultural biotechnology, science- and risk-based regulatory frameworks and efficient authorization processes, in order to facilitate increased trade in such products; and
. acknowledge the importance of each Party adhering to its World Trade Organization (WTO) commitments with respect to the provision of domestic support.

2. Annexes 1-17 set out further commitments.

[appendix]
=== Agricultural Cooperation
1. The Parties intend to strengthen and promote cooperative activities, to be mutually agreed upon by the Parties, in agricultural science and agricultural technology. Such activities may include mutually agreed information exchanges and cooperation. The Parties intend their cooperative activities to be based on, among other things, the principles of integrity, reciprocity, openness, transparency, science, and rule of law.

2. The Parties intend to conduct technical consultations with each other on areas of potential cooperation related to pesticides for agricultural use. These consultations may include discussions of the Parties' pesticide registration data and pesticide trial data, and discussions on the setting of maximum residue levels.

3. The Parties intend to continue implementing and improving the China-United States Scientific Cooperation and Exchange Program to promote further exchanges on agriculturerelated issues between U.S. and Chinese scientific and technical experts. Each Party intends to ensure the participation, as appropriate, of relevant agencies or ministries of its government in activities of the program.

4. The Parties intend to encourage exchanges and dialogues on agricultural topics between, as appropriate, U.S. and Chinese national and sub-national government authorities, farmers, academics, businesses in the agriculture sector, and others. The Parties intend to continue implementation and improvement of existing mechanisms for bilateral communication on agricultural policy, such as the Joint Committee on Cooperation in Agriculture, and to facilitate communication on agricultural policy through participation of officials from both the U.S. and Chinese governments in relevant conferences on this topic, including the China Food Security and Food Safety Strategy Summit and the United States' and China's respective Agricultural Outlook conferences.

5. The Parties intend to promote communication between U.S. and Chinese technical experts on agricultural subjects of mutual interest, including, as appropriate, on production agriculture, crop insurance, trade in agricultural products, sanitary and phytosanitary matters, and rural development.

6. The Parties intend to cooperate in technical discussions, as appropriate, related to sustainable agricultural development.

7. The Parties intend to enhance, as appropriate, their information sharing on animal and plant pests and diseases, including through technical exchange visits. The Parties intend to communicate, as appropriate, their experiences with enhancing capacity to control animal and plant pests and diseases, and through such communication to promote disease detection and the research and development of technologies for the detection and control of such diseases and pests.

8. The Parties intend to engage each other cooperatively on agriculture-related technical, and sanitary and phytosanitary, measures, including on the subject of risk communication. The Parties intend to engage each other cooperatively on these subjects including by increasing cooperation on them in international organizations, such as the WTO, Asia-Pacific Economic Cooperation, the United Nations Food and Agriculture Organization (FAO), and the Codex Alimentarius Commission (Codex).

9. The Parties intend to establish cooperation mechanisms, under the framework of the 2019 _Osaka Declaration on Digital Economy_, for the discussion of ways in which digital technologies can benefit the agriculture sector.

10. The Parties intend to include all relevant agencies of their governments in the governmental activities discussed in this Annex.

11. For greater certainty, nothing in this Annex shall obligate either Party to expend, obligate, or transfer any funds, or to dedicate personnel or other resources to any cooperative activity.

[appendix]
=== Annex 2. Dairy and Infant Formula
1. As soon as practicable following the date of entry into force of this Agreement, the General Administration of Customs of the People's Republic of China (GACC) and the U.S. Food and Drug Administration (FDA) shall initiate bilateral technical discussions to review Import Alert 99-30 "`Detention Without Physical Examination of All Milk Products, Milk Derived Ingredients and Finished Food Products Containing Milk from China due to the Presence of Melamine and/or Melamine Analogs`" in order to clarify the steps necessary for the
removal of Import Alert 99-30.


*_Dairy Products_*

2. Aiming to better meet Chinese consumers' ever-growing needs for dairy products, China shall:

. upon entry into force of this Agreement, allow imports of U.S. dairy products that are:
.. manufactured at a facility on a list compiled by the FDA; and
.. accompanied by an Agricultural Marketing Service (AMS) dairy sanitary certificate;

. within 10 days of the date of entry into force of this Agreement, recognize the U.S. dairy-safety system as providing at least the same level of protection as China's dairy-safety system;

. each time the United States provides China with an updated and complete list of dairy facilities and products under the jurisdiction of the FDA, within 20 working days of receipt of the list:
.. register the facilities and publish the list of facilities and products on the GACC website; and
.. allow U.S. dairy imports into China from those facilities;
. allow imports of U.S. dairy products of bovine, ovine, and caprine origins when accompanied by an AMS dairy sanitary certificate;

. with respect to extended shelf life (ESL) milk:
.. allow ESL milk produced in the United States to be imported and sold as pasteurized milk in China;
.. notify the draft standard to the WTO should China undertake development
of a new standard for ESL milk;
.. ensure that the new standard and all implementing actions are consistent
with China's WTO obligations; and
.. allow imports of U.S. ESL milk consistent with Paragraph 2(a), (c), and (d);
. with respect to fortified milk:
.. allow fortified milk produced in the United States to be imported into China subject to China's National Food Safety Standard - Modified Milk (GB25191), consistent with Paragraph 2(a), (c), and (d);
.. allow such product to be labeled and sold to consumers as "`pasteurizedmodified milk`" provided the product is pasteurized;
.. notify the draft standard to the WTO should China undertake development of a new standard for fortified milk; and
.. ensure that the new standard and all implementing actions are consistent with China's WTO obligations;
. with respect to U.S. ultrafiltered fluid milk:
.. allow U.S. ultrafiltered fluid milk to be imported into China referring to China's National Food Safety Standard - Modified Milk (GB25191), consistent with Paragraph 2(a), (c), and (d) and such products should be labeled with "`ultrafiltration technology`";
.. allow such products to be labeled as "`pasteurized-modified milk`" provided the product is pasteurized;
.. notify the draft standard to the WTO once China develops a draft of a new
standard for ultrafiltered milk; and
.. ensure that the new standard and all implementing actions are consistent with China's WTO obligations; and
. with respect to U.S. dairy permeate powder:
.. within 60 working days of the date of entry into force of this Agreement:
... complete the approval process for U.S. dairy permeate powder for human consumption consistent with the requirements of the _Notice of the General Office of the National Health and Family Planning Commission for Regulating the Review of Imported Foods for Which There Is No Chinese National Food Safety Standards (GuoWeiBanShiPinFa [2017] No.14)_; and
... allow the importation of U.S. dairy permeate powder;
.. notify the draft standard to the WTO should China undertake development of a new standard for dairy permeate powder; and
.. ensure that the new standard and all implementing actions are consistent with China's WTO obligations.

*_Infant Formula_*

3. Aiming to better meet Chinese consumers' ever-growing needs for infant formula products, China shall:

. take into full consideration section 412 of the U.S. Federal Food, Drug, and Cosmetic Act (21 U.S.C. § 350a) and its implementing regulations when China reviews applications for, and decides on, the registration of U.S. infant formula
products;

. accept, complete review of, and issue a decision on product registration applications regardless of whether the submitting entity is associated with an already-registered facility;

. complete technical reviews of infant formula product registration applications and do so ordinarily within 45 working days from receipt of the application;

. normally complete within 40 working days of completing the technical review, provided the U.S. manufacturer provides timely access if needed, any audit, inspection, sampling, or testing that is required in order to register an infant
formula product;

. taking into consideration the FDA's previous product reviews, inspections, and determinations of the regulatory standing of the facility or facilities where the product is manufactured, complete the product registration within 20 working days following completion of the technical review or of any required audit, inspection, sampling, or testing;

. ensure non-disclosure of all trade secrets provided in the infant formula product registration process;

. each time the United States provides China with an updated and complete list of infant formula facilities under the jurisdiction of the FDA, within 20 working days of receipt of the list, register the facilities, publish the list on the GACC website, and allow U.S. infant formula imports into China from those facilities, provided the infant formula product is registered with the State Administration of Market Regulation;

. not require renewal of registration of:

.. infant formula facilities more frequently than once every four years; and
.. infant formula products more frequently than once every five years;

. take into account previous Chinese audit reports, U.S. regulatory information, and any other relevant information, including information provided by the manufacturer, when determining whether a facility inspection is required for
product registration or re-registration; and

. within one week of the date of entry into force of this Agreement, register those U.S. infant formula facilities whose products have been approved in China and that have facility registration applications pending review by the GACC by publishing the complete list of facilities on the GACC website.

*_Audits and Inspections for Dairy Products and Infant Formula_*

4. China shall:

. at least 20 working days in advance of any inspection or audit at a U.S. dairy or infant formula facility, notify the FDA, the U.S. Department of Agriculture (USDA), and the facility;

. to streamline procedures, improve efficiency, and advance trade facilitation, not require an on-site audit or inspection as a pre-requisite to registering a dairy or infant formula facility; and

. ensure that any audit or inspection it conducts for an infant formula product registration or for the registration of a dairy or infant formula facility is for verification of either the U.S. system of oversight or of the ability of the facility to meet the applicable requirements.

5. China continues to have the right to audit the U.S. dairy and infant formula food safety regulatory system, including a representative sample of U.S. dairy and infant formula facilities, in coordination with the FDA. Such auditing shall be risk-based. China also continues to have the right to conduct inspections of a risk-based selection of shipments of U.S. dairy and infant formula products at the port of entry. If China determines, based on scientific inspection, that a particular shipment of U.S dairy or infant formula products is in violation of applicable food safety import requirements, China may refuse importation of that shipment. If China determines that there is a significant, sustained or recurring pattern of non-conformity with an applicable food safety measure by a particular facility, China may refuse to accept shipments from that facility until the problem is resolved. China shall notify the FDA of such non-conformity. The Parties shall exchange information on their dairy and infant formula food safety regulatory systems and other public-health matters.

[appendix]
=== Annex 3. Poultry
1. The Parties shall sign and implement the _Protocol on Cooperation on Notification and Control Procedures for Certain Significant Poultry Diseases_ within 30 days of the date of entry into force of this Agreement.

2. For those U.S. poultry and poultry products imported into China prior to January 1, 2015, China shall, within 30 days of the date of entry into force of this Agreement, issue, based on its previously-conducted assessment of the U.S. regulatory system, a final decision on whether to permit the importation of the product. China shall permit their importation consistently with existing bilaterally-agreed import protocols.

3. China shall maintain measures consistent with the 2018 World Organization for Animal Health (OIE) Terrestrial Animal Health Code Chapter 10.4, or any successor provisions.

4. Within 30 days following receipt from China of a formal request for an evaluation of a region of China for avian disease free recognition and a completed information package to support such a request that addresses the eight factors outlined in 9 CFR Part 92, or any successor provisions, the USDA's Animal and Plant Health Inspection Service (APHIS) shall
initiate such an evaluation.

[appendix]
=== Annex 4. Beef
1. The Parties shall continue implementing the 2017 Protocol for the importation of U.S. beef and beef products into China; however, this Agreement shall prevail over any requirements
in the Protocol that are inconsistent with this Agreement. The two Parties may revise the Protocol according to this Agreement if appropriate.

2. China acknowledges that the United States has submitted all relevant and necessary information as requested by China to enable completion of a risk assessment related to the importation of all U.S. beef, beef products, and pet food containing ruminant ingredients. China shall, within one month of the date of entry into force of this Agreement, eliminate the cattle age requirements for the importation of U.S. beef and beef products.

3. China recognizes the U.S. beef and beef products traceability system. The U.S. Government, in accordance with U.S. regulations, continuously maintains measures, including for traceability, that meet or exceed OIE guidelines for maintaining negligible risk status for the bovine disease addressed in Chapter 11.4 of the 2018 OIE Terrestrial Animal Health Code. Provided the United States maintains its OIE negligible risk classification for that disease, China shall not impose new import restrictions or requirements related to that disease on imports of U.S. beef. Should the United States' negligible risk status change, China shall administer the regulations for imports of U.S. beef in accordance with the 2018 OIE Terrestrial Animal Health Code, Chapter 11.4, Article 11.4.11 or any successor provisions.

4. Aiming to better meet Chinese consumers' ever-growing needs for meat, within one month of the date of entry into force of this Agreement, China shall permit the importation into China of those beef and beef products, except for those listed in Appendix I (Beef, Pork, and Poultry Products Considered Not Eligible for Import into China), inspected by the USDA's Food Safety and Inspection Service (FSIS) in an FSIS-approved facility.

5. Within one month of the date of entry into force of this Agreement, China shall adopt maximum residue limits (MRLs) for zeranol, trenbolone acetate, and melangesterol acetate for imported beef. For beef tissues for which Codex has established MRLs for these hormones, China shall adopt the Codex MRLs. For beef tissues for which Codex has not established MRLs for these hormones, China shall adopt its MRLs by following Codex standards and guidelines and referring to MRLs established by other countries that have performed science-based risk assessments.

[appendix]
=== Annex 5. Live Breeding Cattle
1. Based on the request and information provided by the United States on February 13, 2019, and on March 6, 2019, the Parties shall, within one month of the date of entry into force of this Agreement, commence technical discussions on the preparation of a U.S. export health certificate and a protocol for the importation into China of U.S. breeding cattle, with a view to realizing trade as soon as possible.

[appendix]
=== Annex 6. Pork
1. The Parties intend to promote cooperative activities within the Global African Swine Fever Research Alliance (GARA) to share publicly-available scientific knowledge and information to contribute to the progressive control and eradication of African swine fever (ASF).

2. Aiming to better meet Chinese consumers' ever growing needs for meat, within 10 working days of the date of entry into force of this Agreement China shall permit the importation into China of those pork and pork products inspected by the FSIS in an FSIS-approved facility.

[appendix]
=== Annex 7. Meat, Poultry and Processed Meat
1. Upon entry into force of this Agreement, China shall recognize FSIS oversight of U.S. meat, poultry meat, and processed meat and poultry meat facilities for purposes of allowing imports of U.S. meat, poultry meat, and processed meat and poultry meat.

2. Upon entry into force of this Agreement, China shall accept meat, poultry meat, and processed meat and poultry meat, except for those products listed in Appendix I (Beef, Pork, and Poultry Products Considered Not Eligible for Import into China), inspected by the FSIS in an FSIS-approved facility and accompanied by a FSIS Export Certificate of Wholesomeness (FSIS
9060-5/FSIS 9295-1).

3. Each time the United States provides China with an updated and complete list of FSISapproved facilities, China shall, within 20 working days of receipt, publish the list on the GACC website and allow the importation into China of products from all facilities on the list.

4. China continues to have the right to audit the U.S. meat and poultry food safety regulatory system, including a representative sample of U.S. meat and poultry facilities, in coordination with the FSIS. Such auditing shall be risk-based. China also continues to have the right to conduct inspections of a risk-based selection of shipments of U.S. meat and poultry products at the port of entry. If China determines, based on scientific inspection, that a particular shipment of U.S. meat or poultry products is in violation of applicable food safety import requirements, China may refuse importation of that shipment. If China determines that there is a significant, sustained or recurring pattern of non-conformity with an applicable food safety measure by a particular facility, China may refuse to accept shipments from that facility until the problem is resolved. China shall notify the FSIS of such non-conformity. The Parties shall exchange information on their meat and poultry food safety regulatory systems and other publichealth matters.

5. In consultation with U.S. experts, China shall conduct a risk assessment for ractopamine in cattle and swine as soon as possible without undue delay, and in a manner consistent both with Codex and FAO/World Health Organization (WHO) Joint Expert Committee on Food Additives (JECFA) risk assessment guidance and with the risk assessment for ractopamine previously conducted by the FAO/WHO JECFA. The risk assessment shall be based on verifiable data and the approved conditions of ractopamine use in the United States. China and the United States shall establish a joint working group to discuss the steps to be taken based on the results of the risk assessment.

[appendix]
=== Annex 8. Electronic Meat and Poultry Information System
1. Aiming to streamline trade and deepen cooperation between the United States and China with respect to certification, the GACC shall work with the USDA to finalize the technical requirements for, and to implement, an electronic and automated system for China to access FSIS export certificates accompanying U.S. exports to China of meat, poultry, and meat and poultry products.

2. Provided the United States has implemented the system, and demonstrates the reliability and safety of the system, China shall also implement the system by February 2020. China shall accept via the system all information, including FSIS certificates, necessary to allow shipments of U.S. meat, poultry, and meat and poultry products into China and shall provide relevant certificate information in a timely manner to the Chinese port customs officials.

3. The USDA has a directive permitting replacement certificates in certain instances when appropriate. The GACC shall accept replacement certificates, provided that the FSIS ensures that replacement certificates are clearly identifiable. China shall accept replacement certificates issued by the USDA for situations that include the following:

. the original certificate did not contain required information;
. the original certificate contained typographical errors;
. the importer, exporter, consignee, or consignor changed, but is within the same
country that appears on the original certificate;
. the certificate is lost or damaged; or
. the port of entry changed.

[appendix]
=== Annex 9. Aquatic Products
1. As soon as practicable following the entry into force of this Agreement, the GACC and the FDA shall resume bilateral meetings of the U.S.-China Technical Working Group on Seafood. The Technical Working Group shall identify steps China can take to provide evidence for FDA to assess whether China has controls that would ensure that Chinese aquatic products exported to the United States meet U.S. requirements. The United States confirms that if a Chinese aquatic product producer or exporter submits sufficient evidence to the FDA and the FDA determines that the firm and product should be excluded from Import Alert 16-131, the Chinese aquatic product producer or exporter shall be added to the Green List for Import Alert 16-131.

2. Aiming to better meet Chinese consumers' ever-growing needs for aquatic products, as
soon as practicable following the entry into force of this Agreement, the GACC and the U.S.
National Oceanic and Atmospheric Administration (NOAA) shall meet to discuss the process for
approving the importation into China of the aquatic species that are sold in U.S. interstate
commerce but that are not authorized for sale in China. If the NOAA submits sufficient
evidence to the GACC concerning one of these aquatic species, the GACC shall determine
whether the species is safe to consume and will be allowed to be imported into China.

3. Within 20 working days of the date of entry into force of this Agreement, China shall allow imports into China from those:

. aquatic products facilities considered to be in good regulatory standing by the FDA and also registered by the GACC, when the shipment is accompanied by the bilaterally–agreed certificate issued by the NOAA; and
. fish meal processing facilities considered to be in good regulatory standing by the NOAA and also registered by the GACC, when the shipment is accompanied by the bilaterally-agreed certificate issued by the NOAA.

4. China shall:

. each time the United States provides China with an updated and complete list of aquatic products facilities under the jurisdiction of the FDA, within 20 working days of receipt of the list, register the facilities, publish the list of the facilities on the GACC website, and allow U.S. aquatic product imports into China from those facilities; and
. each time the United States provides China with an updated and complete list of fish meal processing facilities under the jurisdiction of the NOAA, within 20 working days of receipt of the list, register the facilities, publish the list of the
facilities on the GACC website, and allow U.S. fish meal imports into China from those facilities.

5. China continues to have the right to audit the U.S. aquatic products food safety regulatory system, including a representative sample of U.S. aquatic product facilities, in coordination with the FDA. Such auditing shall be risk-based. China also continues to have the right to conduct inspections of a risk-based selection of shipments of U.S. aquatic products at the port of entry. If China determines that a particular shipment of U.S. aquatic products is in violation of applicable food safety import requirements, China may refuse importation of that shipment. If China determines that there is a significant, sustained or recurring pattern of non-conformity with an applicable food safety measure by a particular facility, China may refuse to accept shipments from that facility until the problem is resolved. China shall notify the FDA of such nonconformity. The Parties shall exchange information on their aquatic products food safety regulatory systems and other public-health matters concerning aquatic products.

[appendix]
=== Annex 10. Rice
1. Each time the United States provides China with a list of rice facilities approved by the APHIS as compliant with the Phytosanitary Protocol on the Import of Rice from the United States to China, within 20 working days of receipt of the list, China shall register the facilities, publish the list of facilities, and allow the importation of U.S. rice from each of the APHISapproved rice facilities. China continues to have the right to conduct on-site phytosanitary audits of registered rice facilities.

[appendix]
=== Annex 11. Plant Health
1. Within one month of the date of entry into force of this Agreement, the Parties shall start technical consultations in order to sign, as soon as possible, a phytosanitary protocol on Chinese Bonsai in growing mediums for export to the United States excluding orchids, with a view to realizing trade as soon as possible.

2. Within 45 days of the date of entry into force of this Agreement, USDA/APHIS shall complete its regulatory notice process for imports of Chinese fragrant pear.

3. Within two months of the date of entry into force of this Agreement, USDA/APHIS shall complete its regulatory notice process for imports of Chinese citrus.

4. Within one month of the date of entry into force of this Agreement, USDA/APHIS shall complete its regulatory notice process for imports of Chinese Jujube.

5. Within seven working days of the date of entry into force of this Agreement, USDA/APHIS and the GACC shall sign and implement a phytosanitary protocol to allow the importation of U.S. fresh potatoes for processing into China.

6. Within one month of the date of entry into force of this Agreement, USDA/APHIS and the GACC shall sign and implement a phytosanitary protocol to allow the importation of
California nectarines into China.

7. Within three months of the date of entry into force of this Agreement, USDA/APHIS and the GACC shall sign and implement a phytosanitary protocol to allow the importation of U.S. blueberries into China.

8. Within three months of the date of entry into force of this Agreement, USDA/APHIS and the GACC shall sign and implement a phytosanitary protocol to allow the importation of California Hass avocadoes into China.

9. Within three months of the date of entry into force of this Agreement, USDA/APHIS and the GACC shall sign and implement a phytosanitary protocol to allow the importation of U.S. barley into China. The GACC, in coordination with USDA/APHIS, may conduct an on-site visit of U.S. barley production.

10. Within one month of the date of entry into force of this Agreement, the GACC shall meet with USDA/APHIS and conduct an on-site visit of U.S. production of U.S. alfalfa hay pellets and cubes, U.S. almond meal pellets and cubes, and U.S. timothy hay. Within three months of the date of entry into force of this Agreement, USDA/APHIS and the GACC shall sign and implement a phytosanitary protocol to allow importation into China of these products.

11. The Parties confirm they shall not require a phytosanitary certificate for the importation from the other Party of frozen fruits and vegetables.

12. The Parties shall continue technical consultations concerning facilitation of trade in grain and oilseed products.

[appendix]
=== Annex 12. Feed Additives, Premixes, Compound Feed, Distillers' Dried Grains, and Distillers' Dried Grains with Solubles
1. To streamline procedures, improve efficiencies, and advance trade facilitation, and to better meet demand for feed to promote the development of animal husbandry, China shall:

. not require an on-site audit or inspection as a condition for registering facilities or for approving the importation into China of feed additives, premixes, compound feed products, Distillers' Dried Grains (DDG), and Distillers' Dried Grains with Solubles (DDGS);
. not require an export protocol as a condition for permitting the importation into China of feed additives, premixes, compound feed products, DDG, and DDGS; and
. ensure that its requirements for imports of feed additives, premixes, compound feed products, DDG, and DDGS from the United States are consistent with international standards and guidelines.

2. Each time that the United States provides China with an updated and complete list of U.S. feed additive, premix, compound feed product, DDG, and DDGS facilities, China shall, within 20 working days of receiving the information, register the facilities, publish the list on the GACC website, and allow imports of feed additives, premixes, compound feed products, DDG, and DDGS from U.S. facilities appearing on the list on the GACC website.

3. China shall:

. {blank}
.. within three months of receiving an application from a U.S. DDG or DDGS manufacturer for the approval of the importation into China of one of its products, complete the review of that application; and
.. within 20 working days of completing the review of that application, issue a license allowing importation of the product into China; and
. within 20 working days of receiving an application from a U.S. DDG or DDGS manufacturer that holds or has held a license permitting importation into China of one of its products, but whose license:

.. expired on or after January 1, 2017, or
.. is scheduled to expire after that date, 

issue a license to that manufacturer allowing imports of the product into China.


4. China shall:

. within nine months of receiving an application for the approval of the importation into China of a new feed additive, premix, or compound feed product, complete its review of that application and add the product onto China's List of Feed and
Feed Additives;

. within three months of receiving a new application for the approval of the importation into China of a feed additive, premix, or compound feed product, complete its review of that application and issue a license allowing importation of
the product; and

. within 20 working days of receiving an application for renewal for a feed additive, premix, or compound feed product license, issue a renewed license allowing importation of the product.

5. China continues to have the right to audit the U.S. feed additive, premix, compound feed, DDG, and DDGS feed safety regulatory system, including a representative sample of U.S. feed additive, premix, compound feed, DDG, and DDGS feed facilities, in coordination with the relevant U.S. competent authority. Such auditing shall be risk-based. China also continues to have the right to conduct inspections of a risk-based selection of shipments of U.S. feed additive, premix, compound feed, DDG, and DDGS feed products at the port of entry. If China determines, based on scientific inspection, that a particular shipment of U.S. feed additives, premix, compound feed, DDG, and DDGS feed is in violation of applicable feed safety import requirements, China may refuse importation of that shipment. If China determines that there is a significant, sustained or recurring pattern of non-conformity with an applicable feed safety measure by a particular facility, China may refuse to accept shipments from that facility until the problem is resolved. China shall notify the relevant U.S. competent authority of such nonconformity. The Parties shall exchange information on their feed additive, premix, compound feed, DDG, and DDGS feed safety regulatory systems.

[appendix]
=== Annex 13. Pet Food and Non-ruminant Derived Animal Feed
1. China shall:

. within one month of the date of entry into force of this Agreement:

. lift its ban on U.S. pet food containing ruminant ingredients in accordance with Annex 4.2 (Beef); and
. eliminate the use of Polymerase Chain Reaction (PCR) testing on all U.S. pet food products containing ruminant ingredients, and limit PCR testing of U.S. pet food products not containing ruminant ingredients to a riskbased
selection of shipments;

. upon entry into force of this Agreement, allow the importation of U.S. pet foods containing poultry products;

. not require completion or submission of any facility questionnaire for registration purposes, except that China may request completion of a facility questionnaire with respect to a facility that China is auditing; and

. allow the importation of pet foods with animal-origin ingredients from a 3rd country as long as the ingredients are legally imported into the United States, meet U.S. domestic requirements for inclusion in pet food, and are traceable to the country of origin.

2. Upon entry into force of this Agreement, the Parties shall engage in technical discussions to discuss the importation of U.S. pet food into China. Within two months of the date of entry into force of this Agreement, the Parties shall sign a protocol on U.S. pet food imports into China. Before a new protocol is signed, China shall continue to allow imports of U.S. pet food as detailed in the _Protocol on the Veterinary Health Requirements for Non-Ruminant Derived Animal Feed and Tallow to be Imported from the United States of America to the People's Republic of China_, dated November 18, 2004.

3. China has completed its review of 24 new U.S. pet food and animal feed facilities and shall, within five working days of the date of entry into force of this Agreement, include those facilities on the list of facilities allowed to export to China pet food or non-ruminant derived animal feed.

4. The United States shall, on a monthly basis, provide to China any updates to the list of U.S. pet food and non-ruminant derived animal feed facilities that the United States has determined to be eligible to export pet food or non-ruminant derived animal feed to China. Upon receipt of each update to the list, China shall, within 20 working days, register the facilities, publish the updates to the list of facilities on the GACC website, and allow imports of pet food and non-ruminant derived animal feed from U.S. facilities on the list on the GACC website.

5. China continues to have the right to audit the U.S. pet food and non-ruminant derived animal feed safety regulatory system, including a representative sample of U.S. pet food and non-ruminant derived animal feed facilities, in coordination with the relevant U.S. competent authority. Such auditing shall be risk-based. China also continues to have the right to conduct inspections of a risk-based selection of shipments of U.S. pet food and non-ruminant derived animal feed at the port of entry. If China determines, based on scientific inspection, that a particular shipment of U.S pet food and non-ruminant derived animal feed is in violation of applicable pet food and non-ruminant derived animal feed safety import requirements, China may refuse importation of that shipment. If China determines that there is a significant, sustained or recurring pattern of non-conformity with an applicable feed safety measure by a particular facility, China may refuse to accept shipments from that facility until the problem is resolved. China shall notify the relevant U.S. competent authority of such non-conformity. The Parties shall exchange information on their pet food and non-ruminant derived animal feed safety regulatory systems.

[appendix]
=== Annex 14. Tariff Rate Quotas 
1. China shall ensure that, from December 31, 2019, its TRQ measures for wheat, rice, and corn are in conformity with the Panel Report in _China-Tariff Rate Quotas for Certain Agricultural Products_ and the WTO agreements, including China's commitments under the _Protocol on the Accession of the People's Republic of China_ to the WTO and China's Schedule
CLII, Part I, Section 1(B).

2. The entirety of China's TRQs for wheat, rice, and corn (WRC TRQs) for each year shall be allocated by January 1 of that year to end-users. China shall ensure that it does not inhibit the filling of its WRC TRQs.

3. China's requirements for WRC TRQ eligibility, allocation, return, reallocation, and penalties shall not discriminate between State Trading Enterprises (STEs) and non-STEs and shall apply equally to the STE share of the WRC TRQ and the non-STE share of the WRC TRQ. For the purposes of China's WRC TRQ administration measures, "`end-users`" and "`enterprises`" include STEs when allocated a WRC TRQ.

4. China shall reallocate all unused and returned WRC TRQ amounts, including all unused and returned amounts allocated to STEs or designated as part of the "`STE share,`" by October 1 of each year. Only new applicants and entities other than those returning unused quotas shall be eligible to receive reallocated WRC TRQ amounts.

5. China shall make all WRC TRQ allocations in commercially viable shipping amounts.

6. China shall clearly specify and publish all eligibility criteria for its WRC TRQs and all allocation principles for its WRC TRQ administration, and the allocation principles shall be relevant to the importation, processing, or sale of the commodity subject to the WRC TRQ. China shall ensure that a sufficient number of STE and non-STE entities, including new quota applicants, are eligible to receive WRC TRQ allocations, and that the full utilization of its WRC TRQs is not inhibited.

7. Consistent with China's WTO obligations, at the request of the United States, China shall provide the relevant WRC TRQ allocation and reallocation information requested.

8. Each Party shall make available on a public website existing laws, regulations, and announcements on its administration of WRC TRQs, if any, and publish any change to them in a timely manner. Upon request of a Party, the Parties shall hold consultations on TRQ administration pursuant to the Bilateral Evaluation and Dispute Resolution Chapter.

[appendix]
=== Annex 15. Domestic Support
1. China shall respect its WTO obligations to publish in an official journal its laws, regulations, and other measures pertaining to its domestic support programs and policies.

2. For greater certainty, nothing in this Agreement limits the rights of the United States under the WTO Dispute Settlement Understanding against China with respect to China's domestic support measures.

[appendix]
=== Annex 16. Agricultural Biotechnology
1. To help realize the benefits of agricultural biotechnology for sustainable agriculture, the Parties agree to carry out exchanges on agricultural biotechnology, and intend to take steps to enhance engagement with the public concerning agricultural biotechnology and public awareness of scientific information relevant to agricultural biotechnology, with the aim of building public confidence in, and acceptance of, the use of safe biotechnology in agriculture and the food system.

2. China shall implement a transparent, predictable, efficient, science- and risk-based regulatory process for safety evaluation and authorization of products of agricultural biotechnology. For agricultural biotechnology products for feed or further processing, China shall significantly reduce, to no more than 24 months, the average amount of time between:

. the submission of a formal application for authorization of such a product; and
.  the final decision on approval or disapproval of the product.

China shall base its safety evaluation procedures on the relevant international standards and recommendations of Codex and the International Plant Protection Convention. China shall base any safety evaluation that it conducts on scientific data and information obtained using appropriate methods and analyzed using appropriate statistical techniques.

3. The Parties shall strengthen communication on biotechnology regulation, in order to increase mutual understanding and to facilitate trade in products of agricultural biotechnology.

4. China shall:

. within five working days of receipt of the product dossier submitted in support of a formal application for approval of a product of agricultural biotechnology, prescreen for completeness, by means of comparison against the requirements on the application form, the dossier and inform the applicant of any deficiencies in the sufficiency of information in the dossier;
. accept complaints from applicants concerning the operation of the approval procedure for agricultural biotechnology products to be used for purposes of food, feed, and processing, and take corrective action upon receipt of a justified complaint;
. when additional information from an applicant is necessary for the National Biosafety Committee (NBC) to finalize a safety evaluation, within 20 working days of the NBC meeting at which the NBC ascertained its need for the additional information, request all such information in writing and provide a written
explanation to the applicant of how the requested information would be relevant to the safety of the product's intended use;
. when additional information has been submitted to the NBC by an applicant, ensure that the NBC meets as soon as possible and as often as necessary thereafter in order to finalize the NBC's review of the application; and
. convene at least two NBC meetings per year and increase, depending on the number of applications, the frequency of NBC meetings as much as necessary.

5. China shall establish an authorization period of at least five years for any agricultural biotechnology product.

6. China shall, within 12 months of the date of entry into force of this Agreement, establish and make public a simplified, predictable, science- and risk-based, and efficient safetyassessment procedure for approval of food ingredients derived from genetically modified microorganisms.

7. China shall:

. accept applications for agricultural biotechnology product approvals on an ongoing, year-round basis;
. if prior to receipt by China of a formal application for approval of an agricultural biotechnology product but following the submission of the dossier for the product to U.S. authorities, the dossier for the product is submitted to China, pre-screen the dossier within five working days of receipt for completeness against the Chinese requirements that will apply following the submission of a formal application for approval of the product in China;
. upon receipt of a formal application, begin review of any application for approval of an agricultural biotechnology product;
. not request information unnecessary for assessing the safety of a product for its intended use; and
. for any product that passes China's safety evaluation, make the administrative decision of approval and issue a biosafety certificate within 20 working days of conclusion of the NBC meeting.

8. In the event of an occurrence of low-level presence (LLP) affecting a U.S. shipment exported to China, China shall:
. without undue delay, inform the importer or the importer's agent of the LLP
occurrence and of any additional pertinent information that will be required to be submitted to assist China to make a decision on the management of the LLP occurrence;
. provide to the United States a summary of any risk or safety assessment that
China has conducted in connection with the LLP occurrence;
. ensure that the LLP occurrence is managed without unnecessary delay; and
. take into account any relevant risk or safety assessment provided, and authorization granted, by the United States or any foreign country when deciding how to manage the LLP occurrence.

9. China shall evaluate inadvertent or technically unavoidable LLP occurrences on a case-by-case basis to minimize trade disruptions.

10. The Parties agree to organize experts to conduct further studies on the issue of LLP and to collaborate internationally on practical approaches to addressing LLP.

[appendix]
=== Annex 17. Food Safety
1. The Parties shall not implement food safety regulations, or require actions of the other Party's regulatory authorities, that are not science- or risk-based and shall only apply such regulations and require such actions to the extent necessary to protect human life or health.

[appendix]
=== Appendix I: Beef, Pork, and Poultry Products Considered Not Eligible for Import into China
U.S. statutes and regulations require the condemnation of meat and poultry carcasses, parts thereof, and products, found to be diseased, adulterated or otherwise unfit at the time of slaughter, or during any subsequent inspection. The FSIS does not allow meat or poultry products that are determined to be unqualified, or that are contaminated—for example, with feces, foreign material, or cerebral fluid from cattle—to enter commerce. Animals that display systemic signs of disease or pathologies are condemned. FSIS Public Health Veterinarians certify on the FSIS certificate that the meat or poultry products are from animals that received both antemortem and postmortem inspection and were found sound and healthy. In addition, the product has been inspected and passed as provided by law and regulations of the USDA, and is wholesome, and suitable for human consumption

The following is a list of products that are not eligible for importation into China, including when incorporated into further-processed products:

. beef and pork: thyroid glands, adrenal glands, uropygial glands, tonsils, major lymph nodes exposed during slaughter and cutting, laryngeal muscle tissue, lungs, pancreas, spleen, gallbladder, uterus, hair, hoofs, and lactating mammary glands;

. horns from cattle;

. mechanically separated beef and distal ileum from cattle of any age;

. brain, skull, eyes, trigeminal ganglia, spinal cord, dorsal root ganglia, and vertebral column (excluding the vertebrae of the tail, the transverse processes of the thoracic and lumbar vertebrae, and the wings of the sacrum), from cattle 30 months of age and older; and

. feathers, heads, intestines, and tails of poultry.