
== FINANCIAL SERVICES

=== Article 4.1: Objectives
The Parties believe that they have a significant opportunity for cooperation and mutual benefit in bilateral services trade. Each Party requests that the other Party ensure fair, effective, and non-discriminatory participation in its market for services and services suppliers of the other Party. The Parties shall work constructively to provide fair, effective, and non-discriminatory market access for each other's services and services suppliers. To that end, the Parties shall take specific actions beginning with the actions set forth in this Chapter with respect to the financial services sector.

=== Article 4.2: Banking Services
1. The Parties acknowledge the importance of mutually beneficial cooperation to enhance market access and strengthen the Parties' respective banking services sectors.

2. China commits that when a qualified subsidiary of a U.S. financial institution provides or seeks to provide securities investment fund custody services, its parent company's overseas assets shall be taken into consideration in order to fulfill applicable asset requirements. Within five months after the date of entry into force of this Agreement, China shall allow branches of U.S. financial institutions to provide securities investment fund custody services, and the parent company's overseas assets shall be taken into consideration in order to fulfill applicable asset requirements. China shall review and approve qualified applications by U.S. financial institutions for securities investment fund custody licenses on an expeditious basis.

3. China affirms that U.S. financial institutions applying to serve as Type-A lead underwriters for all types of non-financial debt instruments shall be evaluated and granted licenses based on the revised formula for granting lead underwriting licenses for non-financial enterprise debt instruments, which takes into account U.S. financial institutions' international qualifications in order to fulfill applicable requirements for the entity seeking the license in
China.

4. The United States acknowledges current pending requests by Chinese institutions, including by CITIC Group, and affirms that such requests will be considered expeditiously.


=== Article 4.3: Credit Rating Services
1. China affirms that a wholly U.S.-owned credit rating services supplier has been allowed to rate domestic bonds sold to domestic and international investors, including for the interbank market. China commits that it shall continue to allow U.S. service suppliers, including wholly U.S.-owned credit rating services suppliers, to rate all types of domestic bonds sold to domestic and international investors. Within three months after the date of entry into force of this Agreement, China shall review and approve any pending license applications of U.S. service suppliers to provide credit rating services.

2. Each Party shall allow a supplier of credit rating services of the other Party to acquire a majority ownership stake in the supplier's existing joint venture.

3. The United States affirms that it accords non-discriminatory treatment to Chinese credit rating services suppliers.

=== Article 4.4: Electronic Payment Services
1. China shall accept any applications from a U.S. electronic payment services supplier, including an application of a supplier seeking to operate as a wholly foreign-owned entity, to begin preparatory work to become a bank card clearing institution within five working days of submission, and may make a one-time request within those five working days for any corrections or supplementary information. If such a request is made, China shall accept the application within five working days after the applicant has responded to that request. China shall make a determination with respect to the application, including an explanation of any adverse determination, within 90 working days of its acceptance.

2. No later than one month after a U.S. service supplier notifies China that it has completed its preparatory work, China shall accept the license application of such U.S. supplier, including any license application of Mastercard, Visa, or American Express, and shall make a determination with respect to the application, including an explanation of any adverse determination.

3. The United States affirms it accords non-discriminatory treatment to Chinese electronic payment service suppliers, including UnionPay.

=== Article 4.5: Financial Asset Management (Distressed Debt) Services
1. The Parties acknowledge the mutual beneficial opportunities in the distressed debt services sector and will work together to promote further opportunities in this sector.

2. China shall allow U.S. financial services suppliers to apply for asset management company licenses that would permit them to acquire non-performing loans directly from Chinese banks, beginning with provincial licenses. When additional national licenses are granted, China shall treat U.S. financial services suppliers on a non-discriminatory basis with Chinese suppliers,
including with respect to the granting of such licenses.

3. The United States will continue to allow Chinese financial services suppliers to engage in acquisition and resolution of non-performing loans in the United States.

=== Article 4.6: Insurance Services
1. No later than April 1, 2020, China shall remove the foreign equity cap in the life, pension, and health insurance sectors and allow wholly U.S.-owned insurance companies to participate in these sectors. China affirms that there are no restrictions on the ability of U.S.- owned insurance companies established in China to wholly own insurance asset management companies in China.

2. No later than April 1, 2020, China shall remove any business scope limitations, discriminatory regulatory processes and requirements, and overly burdensome licensing and operating requirements for all insurance sectors (including insurance intermediation), and shall thereafter review and approve expeditiously any application by U.S. financial services suppliers for licenses to supply insurance services. In accordance with this commitment, China affirms that it has eliminated the requirement of thirty-years of insurance business operations for establishment of new foreign insurance companies.

3. The United States acknowledges current pending requests by Chinese institutions, including by China Reinsurance Group, and affirms that such requests will be considered expeditiously.

=== Article 4.7: Securities, Fund Management, Futures Services
1. Each Party shall, on a non-discriminatory basis, review and approve a qualified application of a financial institution of the other Party for a securities, fund management, or futures license. The Parties affirm that licensed financial institutions of the other Party are entitled to supply the same full scope of services in these sectors as licensed financial institutions of the Party.

2. No later than April 1, 2020, China shall eliminate foreign equity limits and allow wholly U.S.-owned services suppliers to participate in the securities, fund management, and futures
sectors.

3. China affirms that it substantially reduced the high net asset value requirement on majority shareholders of securities services suppliers on July 5, 2019.

4. China affirms that existing U.S.-invested securities joint ventures are allowed to retain their existing licenses when they become U.S.-controlled, U.S. majority-owned, or wholly U.S.- owned securities companies.

5. The Parties shall ensure there are no discriminatory restrictions for private fund managers of the other Party. China shall ensure that there is no prohibition on U.S.-owned private fund managers investing in H shares (i.e., shares of mainland Chinese companies listed on the Hong Kong stock exchange) and that qualified U.S.-owned private fund managers may be approved to provide investment advisory services on a case-by-case basis.

6. The Parties affirm that there are no discriminatory restrictions for institutions of the other Party in futures products, including by allowing the institutions of the other Party to invest in the full scope of futures products in which domestic institutions can invest (including financial, interest-rate, and exchange-rate futures).

7. The United States acknowledges current pending requests by Chinese institutions, including by China International Capital Corporation, and affirms that such requests will be considered expeditiously.