
== BILATERAL EVALUATION AND DISPUTE RESOLUTION

=== Article 7.1: Bilateral Evaluation and Dispute Resolution Arrangement
1. To ensure prompt and effective implementation of this Agreement, the Parties establish the following Bilateral Evaluation and Dispute Resolution Arrangement (the "`Arrangement`").

2. The purpose and mandate of the Arrangement are to effectively implement this Agreement, to resolve issues in the economic and trade relationship of the Parties in a fair, expeditious, and respectful manner, and to avoid the escalation of economic and trade disputes and their impact on other areas of the Parties' relationship. The Parties recognize the importance of strengthened bilateral communications in this effort.

=== Article 7.2: Arrangement Structure
1. *High-level Engagement.* The Parties shall create the Trade Framework Group to discuss the implementation of this Agreement, which shall be led by the United States Trade Representative and a designated Vice Premier of the People's Republic of China. The Trade Framework Group shall discuss (a) the overall situation regarding implementation of this Agreement, (b) major problems with respect to implementation, and (c) arrangements for future work between the Parties. The Parties shall resume macroeconomic meetings to discuss overall economic issues, which shall be led by the United States Secretary of the Treasury and the designated Vice Premier of the People's Republic of China. Both Parties shall make every effort to ensure that meetings of the Trade Framework Group and the macroeconomic meetings are efficient and oriented toward solving problems.

2. *Daily Work.* The Arrangement shall include a Bilateral Evaluation and Dispute Resolution Office for each Party.

. For the United States, the Bilateral Evaluation and Dispute Resolution Office shall be headed by a designated Deputy United States Trade Representative. For China, the Bilateral Evaluation and Dispute Resolution Office shall be headed by a designated Vice Minister under the designated Vice Premier.
. Each Party shall designate an official (the "`designated official`") to assist in the work of the Arrangement. By the date of entry into force of this Agreement, each Party shall provide the contact information of its respective designated official. Each Party shall update such information as necessary.
. The Bilateral Evaluation and Dispute Resolution Offices shall (a) assess specific issues relating to implementation of this Agreement, (b) receive complaints regarding implementation submitted by either Party, and (c) attempt to resolve disputes through consultations. In carrying out its work, each Bilateral Evaluation and Dispute Resolution Office may consult with government agencies with relevant expertise.

=== Article 7.3: Requests for Information
A Party may request at any meeting, or prior to a meeting, information from the other Party regarding a matter relating to the implementation of this Agreement. The other Party shall provide a written response containing the requested information. In the event that a Party is not able to provide the requested information, the response shall contain a specific explanation of why the information cannot be provided within the time limit and the specific date when the information will be provided. Nothing in this provision shall obligate a Party to provide confidential information to the other Party.

=== Article 7.4: Dispute Resolution
1. *Appeal.* Where one Party (the "`Complaining Party`") believes that the other Party (the "`Party Complained Against`") is not acting in accordance with this Agreement, the Complaining Party may submit an appeal ("`Appeal`") to the Bilateral Evaluation and Dispute Resolution Office of the Party Complained Against. An Appeal shall be in writing and shall contain sufficient information to allow the Party Complained Against to make a proper assessment of the matter. The Appeal may, but need not, include information that could identify any company at issue or business confidential information. The Appeal and any information and matters related to it are confidential and shall not be shared beyond the Bilateral Evaluation and Dispute Resolution Office, absent the agreement of the Parties.

2. *Scope of Appeal.*
. The dispute resolution process covers all matters that occur after the date of entry into force of this Agreement.
. Any measure, including an action, of a Party taken prior to the date of entry into force of this Agreement, which is maintained or continues to have effect after that date, is also subject to the dispute resolution process. For an Appeal of such a measure, the Complaining Party shall provide to the Party Complained Against an explanation of the continuing effect of the measure.

3. *Assessment.* The Party Complained Against shall carry out and complete an assessment of the Appeal. The Party Complained Against shall consider the facts, nature, and seriousness of
the issues presented by the Appeal. After the assessment is completed, the designated officials shall begin consultations.

4. *Dispute Procedures.* Both Parties will attempt to resolve the Appeal in the most efficient manner using the following procedures:
. If the Appeal cannot be resolved by the designated officials, the concerns may be raised to the designated Deputy United States Trade Representative and the designated Vice Minister. If the Appeal is not resolved at the deputy or viceministerial
level, the Complaining Party may present the issue to the United States Trade Representative and the designated Vice Premier of the People's Republic of China.
. If the concerns of the Complaining Party are not resolved at a meeting between the United States Trade Representative and the designated Vice Premier of the People's Republic of China, the Parties shall engage in expedited consultations on the response to the damages or losses incurred by the Complaining Party. If the Parties reach consensus on a response, the response shall be implemented. If the Parties do not reach consensus on a response, the Complaining Party may resort to taking action based on facts provided during the consultations, including by suspending an obligation under this Agreement or by adopting a remedial measure in a proportionate way that it considers appropriate with the purpose of preventing the escalation of the situation and maintaining the normal bilateral trade relationship. The Party Complained Against can initiate an urgent meeting between the United States Trade Representative and the designated Vice Premier of the People's Republic of China before the effective date of the action to be taken by the Complaining Party. If the Party Complained Against considers that the action by the Complaining Party pursuant to this subparagraph was taken in good faith, the Party Complained Against may not adopt a counter-response, or otherwise challenge such action. If the Party Complained Against considers that the action of the Complaining Party was taken in bad faith, the remedy is to withdraw from this Agreement by providing written notice of withdrawal to the Complaining Party.

5. Notwithstanding the provisions of subparagraph 4(a), if either the United States Trade Representative or the designated Vice Premier of the People's Republic of China considers that an implementation issue is a matter of urgency, either one may raise the matter directly at a meeting between them without prior discussions at lower level meetings. If such a meeting cannot be timely scheduled for this purpose, the Complaining Party may resort to taking action as provided in subparagraph 4(b).

=== Article 7.5: Implementation Period
The Arrangement shall be in effect at the same time as this Agreement and shall remain in place as long as this Agreement is in effect. The Parties may assess the Arrangement and discuss any necessary adjustments to it at Trade Framework Group meetings.

=== Article 7.6: Miscellaneous
1. The Parties affirm their existing rights and obligations with respect to each other under the WTO Agreement and other agreements to which the Parties are party.

2. In the event that a natural disaster or other unforeseeable event outside the control of the Parties delays a Party from timely complying with its obligations under this Agreement, the
Parties shall consult with each other.


[appendix]
=== Annex 7-A: WORKING PROCEDURES OF THE BILATERAL EVALUATION AND DISPUTE RESOLUTION ARRANGEMENT

==== Schedule of Meetings
1. Meetings of the Trade Framework Group shall be held every six months.

2. The macroeconomic meetings shall be held regularly.

3. The heads of each Party's Bilateral Evaluation and Dispute Resolution Office shall meet on a quarterly basis.

4. The designated officials of each Party shall meet at least once a month.

5. During the first two years after this Agreement enters into force, the frequency of meetings may be increased as appropriate. Meetings may be held in person or through any means available to the Parties.


==== Responses to Requests for Information
Pursuant to Article 7.3, a Party shall respond within 15 working days to any requests for information from the other Party.


==== Dispute Resolution Timeline
1. Pursuant to Article 7.4.3, the Party Complained Against shall have 10 working days from
the date of the receipt of the Appeal to carry out and complete an assessment of the Appeal.

2. Pursuant to Article 7.4.4(a):

. The designated officials shall have 21 calendar days from the date of the receipt of the Appeal to reach a resolution.

. If the Appeal is not resolved by the designated officials, the designated Deputy United States Trade Representative and the designated Vice Minister shall have 45 calendar days from the date of the receipt of the Appeal to reach a resolution.

. If the Appeal is not resolved at the deputy or vice-ministerial level and the Complaining Party presents the issue to the United States Trade Representative and the designated Vice Premier of the People's Republic of China, these officials
shall hold a meeting within 30 calendar days from the date the Complaining Party requests such a meeting.

3. Pursuant to Article 7.4.5, if either the United States Trade Representative or the designated Vice Premier of the People's Republic of China requests to meet on a matter of
urgency, a meeting shall be scheduled within 30 calendar days from the date of receipt of that request.

4. The Parties may agree, in writing, to extend the time periods set forth in this Annex.

5. The calculation of working days in this Annex is based on the official calendar of the government of the Party Complained Against.