
== FINAL PROVISIONS


=== Article 8.1: Annexes, Appendices, and Footnotes
The annexes, appendices, and footnotes to this Agreement constitute an integral part of this Agreement.


=== Article 8.2: Amendments
1. The Parties may agree, in writing, to amend this Agreement.

2. An amendment shall enter into force 60 days after the date on which the Parties exchange written notifications of the approval of the amendment in accordance with their respective applicable domestic procedures, or such other date as the Parties may decide.


=== Article 8.3: Entry into Force and Termination
1. This Agreement shall enter into force within 30 days of signature by both Parties or as of the date on which the Parties have notified each other in writing of the completion of their respective applicable domestic procedures, whichever is sooner.

2. Either Party may terminate this Agreement by providing written notice of termination to the other Party. The termination shall take effect 60 days after the date on which a Party has provided that written notice to the other Party, or on such other date as the Parties may decide.


=== Article 8.4: Further Negotiations
The Parties will agree upon the timing of further negotiations.


=== Article 8.5: Notice and Comment on Implementing Measures
Except as otherwise provided in this Agreement, each Party shall provide no less than 45 days for public comment on all proposed measures implementing this Agreement. Each Party shall consider concerns raised by the other Party in any final measure or amendment intended to implement this Agreement.


=== Article 8.6: Authentic Texts
The English and Chinese versions of this Agreement are equally authentic.